version: '3'
services:
  meteor:
    build:
      context: ./meteor/
    ports:
      - "3010:3000"
    links:
      - mongo
      - api
    env_file:
      - .env
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api/
    ports:
      - "8081:8080" # if access id needed from the outside (otherwise no need)
  neo4j:
    image: neo4j:5.7.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_server_https_advertised__address=localhost:7473
      - NEO4J_server_http_advertised__address=localhost:7474
      - NEO4J_server_bolt_advertised__address=localhost:7687
