services:
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: alloy4fun-api
    build:
      context: ./api
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017/meteor
  meteor:
    container_name: alloy4fun-meteor
    build:
      context: ./meteor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - api
    links:
      - mongo
      - api
    environment:
      - MONGO_URL=mongodb://mongo:27017/meteor
      - METEOR_SETTINGS= {"env":{"API_URL":"http://alloy4fun-api:8080"}}
