services:
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: alloy4fun-api
    build:
      context: ./api
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - mongo
    ports:
      - "8080:8080" # if access id needed from the outside (otherwise no need)
    links:
      - mongo
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing the host from within the container
  meteor:
    container_name: alloy4fun-meteor
    build:
      context: ./meteor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - api
    links:
      - mongo
      - api
