version: '3'
services:
#  meteor:
#    build:
#      context: ./meteor/
#    ports:
#      - "3010:3000"
#    links:
#      - mongo
#      - api
#    env_file:
#      - .env
#    depends_on:
#      mongo:
#        condition: service_healthy

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    image: quarkus/alloy4fun-api-jvm
    ports:
      - "8080:8080" # if access id needed from the outside (otherwise no need)
    links:
      - mongo