version: '3'
services:
#  meteor:
#    build:
#      context: ./meteor/
#    ports:
#      - "3010:3000"
#    links:
#      - mongo
#      - api
#    env_file:
#      - .env
#    depends_on:
#      mongo:
#        condition: service_healthy

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    image: quarkus/alloy4fun-api-jvm
    ports:
      - "8080:8080" # if access id needed from the outside (otherwise no need)
    links:
      - mongo
      - neo4j
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
#      - URI_NEO4J=${URI_NEO4J_HOST} # for accessing neo4j running on the host
      - URI_NEO4J=${URI_NEO4J_DOCKER} # for accessing neo4j running in a docker container
      - USERNAME_NEO4J=${USERNAME_NEO4J}
      - PASSWORD_NEO4J=${PASSWORD_NEO4J}
#    extra_hosts:
#      - "host.docker.internal:host-gateway" # for accessing the host from within the container
  neo4j:
    image: neo4j:5.7-enterprise
    tty: true
    stdin_open: true
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j/data:/data # for storing data
      - ./data/neo4j/logs:/logs # for storing logs
      - ./data/neo4j/import:/var/lib/neo4j/import # where to import data from
      - ./data/neo4j/plugins:/plugins # where to store plugins like apoc (required by higena)
      - ./data/neo4j/conf/:/var/lib/neo4j/conf/ # where the config file is stored
    environment:
      - NEO4J_AUTH=${USERNAME_NEO4J}/${PASSWORD_NEO4J} # sets username and password for neo4j for the first time the container is created
      - NEO4J_dbms_max__databases=200 # for using multiple databases. increase if needed
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # for using enterprise edition
      - NEO4J_dbms_security_procedures_unrestricted=jwt.security.*,apoc.*,gds.* # used by higena for graph algorithms
      - NEO4J_server_directories_import=import # import folder
      - NEO4J_server_directories_run=run # avoid PID errors
      - NEO4J_server_memory_heap_initial__size=5G # increase if needed
      - NEO4J_server_memory_heap_max__size=5G # increase if needed
    env_file:
      - .env

    